# Workshop Tutorial

## Numpy 

This imports both the pandas and the numpy python libraries

In [1]:
import pandas as pd
import numpy as np

/usr/local/lib/python2.7/dist-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/usr/local/lib/python2.7/dist-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/usr/local/lib/python2.7/dist-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/usr/local/lib/python2.7/dist-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/usr/local/lib/python2.7/dist-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate bi

Let's create our first array!

In [2]:
a = np.array([1, 4, 5, 8], float)
print(a)

[1. 4. 5. 8.]


Time to move to two-dimensions

In [3]:
a = np.array([[1,2],[3,4]], float)
print(a)

[[1. 2.]
 [3. 4.]]


Properties of arrays:

In [4]:
print(a.shape)
print(a.dtype)
print(2 in a)
print(50 in a)

(2, 2)
float64
True
False


In [5]:
a = a.reshape(1,4)
print(a)
a = a.reshape(2,2)
print(a)

[[1. 2. 3. 4.]]
[[1. 2.]
 [3. 4.]]


Manipulating array content:

In [6]:
a_val = a[1,1]
print(a_val)

4.0


In [7]:
a = np.array([[1,2,3], [4,5,6]], float)
print(a)
print(a[1,:])
print(a[:, 2])

[[1. 2. 3.]
 [4. 5. 6.]]
[4. 5. 6.]
[3. 6.]


Creating filler arrays with ones or zeros:

In [8]:
b = np.zeros((2,3), dtype=int)
print(b)
c = np.ones((5, 2), dtype=float)
print(c)

[[0 0 0]
 [0 0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
d = np.ones_like(a)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


## Pandas

Use pandas for large data sets while numpy is better for mathematical operations on smaller matrices

Uses dataframes instead of arrays. Let's make a dataframe:

In [10]:
data = np.array([['','A', 'B', 'C'],
                 ['Row0', 1, 2, 3],
                 ['Row1', 3, 4, 5],
                 ['Row2', 6, 7, 8]])

df = pd.DataFrame(data=data[1:,1:],
                  index=data[1:,0],
                  columns=data[0,1:])

print(df)

      A  B  C
Row0  1  2  3
Row1  3  4  5
Row2  6  7  8


Let's try locating and printing different values in our dataframe

In [11]:
print(df.iloc[0][0])
print(df.iloc[1:])

1
      A  B  C
Row1  3  4  5
Row2  6  7  8


iloc gets rows (or columns) at particular positions in the index

In [12]:
print(df.loc['Row1'][2])
print(df.loc[:]['B'])

5
Row0    2
Row1    4
Row2    7
Name: B, dtype: object


loc gets rows (or columns) with particular labels from the index